### ISSUE TITLE
Not intercepting touches on clickable views

### ISSUE THREAD

**Issue by frodberserk** [blipinsk/RecyclerViewHeader#4]
Hi, thanks for the library. I am facing a problem here. I attached a header view which has some clickable views. If I try to scroll by touching that views, the view doesn't scroll. Please provide solution for this.

**Comment by blipinsk** [comment]
Issue has been fixed.
If you need this to be working correctly right now, download the code from `develop` branch.

It will be introduced as a part of `1.2` release.

Cheers.

**Comment by frodberserk** [comment]
Thanks! But the header is very buggy. Sometimes when a keyboard opens on some edit text, the header portion behind the keyboard becomes white when I scroll the screen.

**Comment by blipinsk** [comment]
It's valuable input. Please tell me more about the problem. Is this `EditText` a part of the header or one of the `RecyclerView` items?

**Comment by frodberserk** [comment]
My header is a Relative layout with some TextViews and some images. Also there is an image which loads from web. Actually my layout is following:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/app_background"
    android:orientation="vertical">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimaryDark">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <ImageView
                android:id="@+id/comments_back"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:src="@drawable/abc_ic_ab_back_mtrl_am_alpha" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:textSize="16sp"
                android:layout_marginLeft="16dp"
                android:textColor="@android:color/white" />
        </LinearLayout>
    </android.support.v7.widget.Toolbar>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_below="@+id/toolbar"
        android:layout_height="match_parent"
        android:layout_above="@+id/comments_text_send">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/comments_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <com.codebrew.fush.utils.RecyclerViewHeader
            android:id="@+id/header"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <include
                    android:id="@+id/feed_header"
                    layout="@layout/row_feed" />

                <include
                    android:id="@+id/comments_progress"
                    layout="@layout/progress_bar"
                    android:layout_width="24dp"
                    android:layout_height="24dp"
                    android:layout_gravity="center" />
            </LinearLayout>
        </com.codebrew.fush.utils.RecyclerViewHeader>
    </FrameLayout>

    <include
        android:id="@+id/comments_text_send"
        layout="@layout/include_text_send"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true" />

</RelativeLayout>

**Comment by frodberserk** [comment]
The layout include_text_send.xml is a LinearLayout with orientation:horizontal, having an EditText and an ImageView(like chat box). The layout row_feed.xml is:

    <?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/app_background">

    <View
        android:id="@+id/separator"
        android:layout_width="match_parent"
        android:layout_height="1px"
        android:background="@color/app_separator" />

    <RelativeLayout
        android:id="@+id/feed_info_frame"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/separator"
        android:layout_toLeftOf="@+id/feed_more">

        <include
            android:id="@+id/feed_avatar"
            layout="@layout/include_avatar_view" />

        <TextView
            android:id="@+id/feed_username"
            android:layout_marginTop="@dimen/row_feed_margin"
            android:singleLine="true"
            android:layout_toRightOf="@id/feed_avatar"
            android:textStyle="bold"
            android:text="Vendetta"
            android:textColor="@color/app_color"
            android:textSize="18sp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

        <TextView
            android:id="@+id/feed_college"
            android:maxLines="2"
            android:layout_toRightOf="@id/feed_avatar"
            android:textStyle="bold"
            android:text="UIET, Panjab University, Chandigarh"
            android:textColor="@color/app_grey_dark"
            android:layout_below="@id/feed_username"
            android:textSize="12sp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

        <ImageView
            android:visibility="gone"
            android:id="@+id/feed_gender"
            android:layout_marginLeft="4dp"
            android:layout_alignTop="@id/feed_username"
            android:layout_alignBottom="@id/feed_username"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_toRightOf="@id/feed_username" />

        <TextView
            android:id="@+id/feed_anonymous"
            android:padding="16dp"
            android:textStyle="bold"
            android:text="Someone posted"
            android:textColor="@color/app_grey_dark"
            android:textSize="14sp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />
    </RelativeLayout>

    <ImageView
        android:padding="8dp"
        android:id="@+id/feed_more"
        android:layout_alignParentRight="true"
        android:src="@drawable/ic_more_grey"
        android:layout_below="@id/separator"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <TextView
        android:id="@+id/feed_time"
        android:singleLine="true"
        android:gravity="center"
        android:layout_alignTop="@id/feed_more"
        android:layout_alignBottom="@id/feed_more"
        android:layout_toLeftOf="@id/feed_more"
        android:layout_below="@id/separator"
        android:textStyle="bold"
        android:text="2 days ago"
        android:textColor="@color/app_grey_dark"
        android:textSize="12sp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <TextView
        android:id="@+id/feed_text"
        android:paddingLeft="@dimen/row_feed_margin"
        android:paddingRight="@dimen/row_feed_margin"
        android:layout_marginTop="4dp"
        android:layout_below="@id/feed_info_frame"
        android:textColor="@color/app_color"
        android:textSize="14sp"
        android:background="@color/app_background"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <com.codebrew.fush.utils.ByThirdImageView
        android:layout_marginTop="@dimen/row_feed_margin"
        android:id="@+id/feed_image"
        android:scaleType="centerCrop"
        android:src="@drawable/clg_bg"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/feed_text" />

    <TextView
        android:id="@+id/feed_upvotes_and_comments"
        android:layout_marginLeft="@dimen/row_feed_margin"
        android:paddingBottom="@dimen/row_feed_margin"
        android:paddingTop="@dimen/row_feed_margin"
        android:singleLine="true"
        android:textStyle="bold"
        android:text="124 upvotes    213 comments"
        android:textColor="@color/app_grey_dark"
        android:layout_below="@id/feed_image"
        android:textSize="12sp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <ImageView
        android:paddingLeft="8dp"
        android:paddingRight="8dp"
        android:id="@+id/feed_upvote"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_upvote_normal"
        android:layout_alignLeft="@id/feed_upvotes_and_comments"
        android:layout_below="@id/feed_upvotes_and_comments" />

    <ImageView
        android:paddingLeft="8dp"
        android:paddingRight="8dp"
        android:id="@+id/feed_downvote"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_downvote_normal"
        android:layout_toRightOf="@id/feed_upvote"
        android:layout_below="@id/feed_upvotes_and_comments" />

    <ImageView
        android:paddingLeft="8dp"
        android:paddingRight="8dp"
        android:id="@+id/feed_comment"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/pressable_comment"
        android:layout_toRightOf="@id/feed_downvote"
        android:layout_below="@id/feed_upvotes_and_comments" />

    <ImageView
        android:id="@+id/feed_my_campus"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/mycampus"
        android:layout_alignParentRight="true"
        android:layout_alignTop="@id/feed_upvote"
        android:layout_alignBottom="@id/feed_upvote" />

</RelativeLayout>

**Comment by blipinsk** [comment]
I will be investigating the `EditText` keyboard-related bug in a separate issue.

I'm closing this one since the issue described here (originally) is fixed.

**Comment by frodberserk** [comment]
Sure. But sometimes it doesn't even scroll. So, the original issue still remains.

**Comment by blipinsk** [comment]
When it doesn't scroll? It works for me every single time.

**Comment by frodberserk** [comment]
Well, it happened sometimes. Maybe I was doing something wrong. I will check once more and will tell you.

**Comment by blipinsk** [comment]
Thanks :)
